// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Content: typeof import('./pages/dashboard/components/Content.vue')['default']
    Dark: typeof import('./components/Dark.vue')['default']
    FooterContent: typeof import('./components/FooterContent.vue')['default']
    Language: typeof import('./components/Language.vue')['default']
    MainTitle: typeof import('./pages/dashboard/components/MainTitle.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    SideMenu: typeof import('./components/SideMenu.vue')['default']
    TeamCard: typeof import('./pages/dashboard/components/TeamCard.vue')['default']
  }
}

export { }
