// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Content: typeof import('./components/main/Content.vue')['default']
    FooterContent: typeof import('./components/FooterContent.vue')['default']
    MainTitle: typeof import('./components/main/MainTitle.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    SideMenu: typeof import('./components/SideMenu.vue')['default']
    TeamCard: typeof import('./components/main/TeamCard.vue')['default']
    V1: typeof import('./components/V1.vue')['default']
  }
}

export { }
