// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es/el-aside')['default']
    ElButton: typeof import('element-plus/es/el-button')['default']
    ElContainer: typeof import('element-plus/es/el-container')['default']
    ElIcon: typeof import('element-plus/es/el-icon')['default']
    ElMenu: typeof import('element-plus/es/el-menu')['default']
    ElMenuItem: typeof import('element-plus/es/el-menu-item')['default']
    ElMenuItemGroup: typeof import('element-plus/es/el-menu-item-group')['default']
    ElSubmenu: typeof import('element-plus/es/el-submenu')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}

export { }
